---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-pfsense-controller.fullname" . }}
  labels:
    {{- include "kubernetes-pfsense-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  pfsense-password: {{ .Values.pfsense.password | quote }}
